# Generated by Django 5.2.3 on 2025-06-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.CharField(
                        help_text="Введите email получателя рассылки",
                        max_length=100,
                        unique=True,
                        verbose_name="Получатель рассылки",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        help_text="Введите Ф.И.О получателя рассылки",
                        max_length=200,
                        null=True,
                        verbose_name="Ф.И.О. получателя рассылки",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Владелец(Пользователь)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
                "ordering": ["email"],
            },
        ),
    ]
