# Generated by Django 5.2.3 on 2025-06-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Дата и время начала отправки рассылки", verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Необязательно. Если указано, рассылка прекратится после этой даты.",
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mailings", to="mailings.message"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Владелец(Пользователь)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_mailings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="received_mailings",
                        to="mailings.mailingrecipient",
                        verbose_name="Получатели рассылки",
                    ),
                ),
            ],
            options={
                "ordering": ["owner", "start_at", "end_at"],
            },
        ),
    ]
