# Generated by Django 5.2.3 on 2025-06-12 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingRecipient",
            new_name="Recipient",
        ),
    ]
