# Generated by Django 5.2.3 on 2025-06-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_rename_mailingrecipient_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["start_at", "end_at"]},
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_at",
            field=models.DateTimeField(
                help_text="Введите дату и время в формате: 'гггг-мм-дд чч-мм'",
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "datetime_attempt",
                    models.DateTimeField(
                        help_text="Дата и время в формате: 'гггг-мм-дд чч-мм'", verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        default=None,
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Ответ почтового сервера на отправку",
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная рассылка",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "ordering": ["datetime_attempt"],
            },
        ),
    ]
