# Generated by Django 5.2.3 on 2025-06-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_mailing_options_alter_mailing_start_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="datetime_attempt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                default=1,
                help_text="Связанная рассылка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                default=None,
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
