# Generated by Django 5.2.3 on 2025-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailingattempt_datetime_attempt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["start_at", "end_at", "is_periodic"]},
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_periodic",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Периодическая рассылка"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_run",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Следующий запуск"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно"), ("monthly", "Ежемесячно")],
                max_length=10,
                null=True,
            ),
        ),
    ]
