# Generated by Django 5.2.3 on 2025-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_alter_mailing_options_mailing_is_periodic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[("DAILY", "Ежедневно"), ("WEEKLY", "Еженедельно"), ("MONTHLY", "Ежемесячно")],
                max_length=10,
                null=True,
            ),
        ),
    ]
