# Generated by Django 5.2.3 on 2025-06-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_alter_mailing_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_at", "end_at", "is_periodic"],
                "permissions": [
                    ("can_view_mailings", "Can view mailings"),
                    ("can_disable_mailings", "Can disable mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["datetime_attempt"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
    ]
