# Generated by Django 5.2.3 on 2025-06-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_alter_mailing_options_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_create_recipients", "Can create recipients"),
                    ("can_view_recipients", "Can view recipients"),
                    ("can_update_recipients", "Can update recipients"),
                    ("can_delete_recipients", "Can delete recipients"),
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
