# Generated by Django 5.2.3 on 2025-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0010_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_at", "end_at", "is_periodic"],
                "permissions": [("can_disable_mailings", "Can disable mailings")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"ordering": ["email"], "verbose_name": "получатель", "verbose_name_plural": "получатели"},
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, help_text="Отключение рассылок", null=True),
        ),
    ]
