# Generated by Django 5.2.3 on 2025-06-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_alter_mailing_options_alter_recipient_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                help_text="Владелец(Пользователь)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
