# Generated by Django 5.2.3 on 2025-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0012_alter_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Выберите дату и время завершения рассылки",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Отключение рассылки. Выберите нужный вариант",
                null=True,
                verbose_name="Рассылка активна ('Да/Нет')",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_at",
            field=models.DateTimeField(
                help_text="Выберите дату и время начала рассылки", verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(help_text="Введите тему письма", max_length=200, verbose_name="Тема сообщения"),
        ),
    ]
