# Generated by Django 5.2.3 on 2025-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(
                blank=True, default=False, help_text="Добавление пользователю статуса 'менеджер'", null=True
            ),
        ),
    ]
