# Generated by Django 5.2.3 on 2025-06-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_users", "Can block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
