# Generated by Django 5.2.3 on 2025-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="Email пользователя", max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="✅Активен/◻️Неактивен (Снять отметку, сделав пользователя неактивным)",
                verbose_name="",
            ),
        ),
    ]
